### ISSUE TITLE
Buttons Please

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/TemplateDocs#8]
Hey @MattReimer or @philipbaileynar. I really like how you have a nice custom button on [this page on GCD](http://gcd.riverscapes.xyz/known-bugs.html):
![2018-03-20_221952](https://user-images.githubusercontent.com/9723905/37694450-e8bb1d96-2c8c-11e8-98b3-9df2b88fb480.png)

I see that you used a button in the [md code](https://github.com/Riverscapes/gcd/edit/master/docs/known-bugs.md):
``` md
<a class="button large expanded" href="https://github.com/Riverscapes/gcd/issues"><i class="fa fa-github"/> Github Issues</a>
```
On this specifically, I wonder if we should filter the issues by 'bugs': https://github.com/Riverscapes/gcd/issues?q=is%3Aopen+is%3Aissue+label%3Abug

# Request

Can you show @lhaycock  and I how to specify and make these buttons please? It seems like this should be added to your http://riverscapes.northarrowresearch.com/Technical_Reference/applying_theme.html documentation.... 

I can see us having these for lots of things (e.g. downloads, issues, etc.). 

I made a crappy one I need to fix:
![riverscapes_downloadgithub](https://user-images.githubusercontent.com/9723905/37694513-6b336c38-2c8d-11e8-83f3-aa62713e98f9.png)

**Comment by MattReimer** [comment]
Hey @joewheaton, @lhaycock . Buttons are just styled versions from the foundation toolkit:

Full docs here:

<https://foundation.zurb.com/sites/docs/button.html>

I know the one you made was hastily done but I would avoid the complexity of multiple font-sizes, icons, lines breaks, text-cases etc. 

All foundation components are designed specifically to fight semantic complexity so that they are guaranteed to look as good on a phone as a desktop computer.

**Comment by MattReimer** [comment]
More followup:

I've added back the styleguide to the template docs:

<https://riverscapes.github.io/TemplateDocs/styleguide.html>

We can demo how things look and how to use them that way
